In [19]:
import pandas as pd
import os

Day 10-1. 데이터 조작법 익히기

In [20]:
# COVID 데이터 경로지정
pt = os.getcwd()
print(pt)    
# 출력: '/content'
covid_path = "/Users/chae/Documents/GitHub/2023-24_Severance_Hospital/WikiDocs_의료영상_인공지능의_모든것/III_정형데이터_다루기/dataset/COVID clinical trials.csv"
df = pd.read_csv(covid_path)

/Users/chae/Documents/GitHub/2023-24_Severance_Hospital/WikiDocs_의료영상_인공지능의_모든것/III_정형데이터_다루기

In [21]:
df.head()

,Rank,NCT Number,Title,Acronym,Status,Study Results,Conditions,Interventions,Outcome Measures,Sponsor/Collaborators,...,Other IDs,Start Date,Primary Completion Date,Completion Date,First Posted,Results First Posted,Last Update Posted,Locations,Study Documents,URL
0,1,NCT04785898,Diagnostic Performance of the ID Now™ COVID-19...,COVID-IDNow,"Active, not recruiting",No Results Available,Covid19,Diagnostic Test: ID Now™ COVID-19 Screening Test,Evaluate the diagnostic performance of the ID ...,Groupe Hospitalier Paris Saint Joseph,...,COVID-IDNow,"November 9, 2020","December 22, 2020","April 30, 2021","March 8, 2021",NaN,"March 8, 2021","Groupe Hospitalier Paris Saint-Joseph, Paris, ...",NaN,https://ClinicalTrials.gov/show/NCT04785898
1,2,NCT04595136,Study to Evaluate the Efficacy of COVID19-0001...,COVID-19,Not yet recruiting,No Results Available,SARS-CoV-2 Infection,Drug: Drug COVID19-0001-USR|Drug: normal saline,Change on viral load results from baseline aft...,United Medical Specialties,...,COVID19-0001-USR,"November 2, 2020","December 15, 2020","January 29, 2021","October 20, 2020",NaN,"October 20, 2020","Cimedical, Barranquilla, Atlantico, Colombia",NaN,https://ClinicalTrials.gov/show/NCT04595136
2,3,NCT04395482,Lung CT Scan Analysis of SARS-CoV2 Induced Lun...,TAC-COVID19,Recruiting,No Results Available,covid19,Other: Lung CT scan analysis in COVID-19 patients,A qualitative analysis of parenchymal lung dam...,University of Milano Bicocca,...,TAC-COVID19,"May 7, 2020","June 15, 2021","June 15, 2021","May 20, 2020",NaN,"November 9, 2020","Ospedale Papa Giovanni XXIII, Bergamo, Italy|P...",NaN,https://ClinicalTrials.gov/show/NCT04395482
3,4,NCT04416061,The Role of a Private Hospital in Hong Kong Am...,COVID-19,"Active, not recruiting",No Results Available,COVID,Diagnostic Test: COVID 19 Diagnostic Test,Proportion of asymptomatic subjects|Proportion...,Hong Kong Sanatorium & Hospital,...,RC-2020-08,"May 25, 2020","July 31, 2020","August 31, 2020","June 4, 2020",NaN,"June 4, 2020","Hong Kong Sanatorium & Hospital, Hong Kong, Ho...",NaN,https://ClinicalTrials.gov/show/NCT04416061
4,5,NCT04395924,Maternal-foetal Transmission of SARS-Cov-2,TMF-COVID-19,Recruiting,No Results Available,Maternal Fetal Infection Transmission|COVID-19...,Diagnostic Test: Diagnosis of SARS-Cov2 by RT-...,COVID-19 by positive PCR in cord blood and / o...,Centre Hospitalier Régional d'Orléans|Centre d...,...,CHRO-2020-10,"May 5, 2020",May 2021,May 2021,"May 20, 2020",NaN,"June 4, 2020","CHR Orléans, Orléans, France",NaN,https://ClinicalTrials.gov/show/NCT04395924

In [22]:
df ['area'] = "seoul"
df [[ 'Rank' , 'area' ]].head()

   Rank   area
0     1  seoul
1     2  seoul
2     3  seoul
3     4  seoul
4     5  seoul

In [23]:
df.rename(columns={ 'area': 'city' }, inplace=True)
df.columns

Index(['Rank', 'NCT Number', 'Title', 'Acronym', 'Status', 'Study Results',
       'Conditions', 'Interventions', 'Outcome Measures',
       'Sponsor/Collaborators', 'Gender', 'Age', 'Phases', 'Enrollment',
       'Funded Bys', 'Study Type', 'Study Designs', 'Other IDs', 'Start Date',
       'Primary Completion Date', 'Completion Date', 'First Posted',
       'Results First Posted', 'Last Update Posted', 'Locations',
       'Study Documents', 'URL', 'city'],
      dtype='object')

In [24]:
df [ 'city' ].head()

0    seoul
1    seoul
2    seoul
3    seoul
4    seoul
Name: city, dtype: object

In [25]:
df.Status.value_counts()

Status
Recruiting                   2805
Completed                    1025
Not yet recruiting           1004
Active, not recruiting        526
Enrolling by invitation       181
Withdrawn                     107
Terminated                     74
Suspended                      27
Available                      19
No longer available            12
Approved for marketing          2
Temporarily not available       1
Name: count, dtype: int64

In [26]:
df[(df[ 'Rank' ] > 5000) & ( df ['Conditions'] == 'Covid19') ]

,Rank,NCT Number,Title,Acronym,Status,Study Results,Conditions,Interventions,Outcome Measures,Sponsor/Collaborators,...,Start Date,Primary Completion Date,Completion Date,First Posted,Results First Posted,Last Update Posted,Locations,Study Documents,URL,city
5065,5066,NCT04597216,Exploration of Feasability of Blood and Saliva...,NanoDxCoV19,Recruiting,No Results Available,Covid19,Device: sample of blood and saliva,Feasibility of proteomic profile|Interest of p...,"University Hospital, Grenoble",...,"October 15, 2020","December 31, 2020","December 31, 2021","October 22, 2020",NaN,"October 22, 2020","olivier EPAULARD, Grenoble, France",NaN,https://ClinicalTrials.gov/show/NCT04597216,seoul
5083,5084,NCT04837755,CORONA in the Saarland,CORSAAR,Recruiting,No Results Available,Covid19,Diagnostic Test: Cytokine measurements,Correlation of biomarkers with mortality and d...,Universität des Saarlandes,...,"March 1, 2020","December 31, 2025","December 31, 2025","April 8, 2021",NaN,"April 8, 2021","Saarland University, Homburg, Saarland, Germany",NaN,https://ClinicalTrials.gov/show/NCT04837755,seoul
5084,5085,NCT04681261,"Occupational Balance, Fear and Agoraphobia",OB,Completed,No Results Available,Covid19,Other: this study is not an intervention study,Occupational Balance Questionnaire,Hacettepe University,...,"May 4, 2020","June 4, 2020","June 4, 2020","December 23, 2020",NaN,"December 23, 2020","Özgü İnal, Edirne, Merkez, Turkey",NaN,https://ClinicalTrials.gov/show/NCT04681261,seoul
5086,5087,NCT04802187,Implementation of SARS-CoV Testing Strategies ...,NaN,Recruiting,No Results Available,Covid19,Other: RADx CHCs testing intervention strategy...,Percentage increase in testing during the stud...,Massachusetts General Hospital|Dana-Farber Can...,...,"December 1, 2020","August 31, 2022","August 31, 2022","March 17, 2021",NaN,"March 17, 2021",Massachusetts League of Community Health Cente...,NaN,https://ClinicalTrials.gov/show/NCT04802187,seoul
5100,5101,NCT04490239,Intranasal Heparin Tolerability Study,NaN,"Active, not recruiting",No Results Available,Covid19,Drug: Intranasal heparin sodium (porcine),"activated partial thromboplastin time (aPTT), ...","Joshua Sharp|University of Mississippi, Oxford",...,"October 9, 2020",November 2020,November 2020,"July 29, 2020",NaN,"October 14, 2020",The University of Mississippi National Center ...,NaN,https://ClinicalTrials.gov/show/NCT04490239,seoul
5101,5102,NCT04776174,Efficacy and Tolerance of Telerobotic vs Stand...,NaN,Not yet recruiting,No Results Available,Covid19,Device: Ultrasound using the telerobotic Melod...,Number of normal and abnormal standard and tel...,Centre Hospitalier Intercommunal Creteil|ADECH...,...,"March 1, 2021","October 30, 2021",January 2022,"March 1, 2021",NaN,"March 1, 2021",NaN,NaN,https://ClinicalTrials.gov/show/NCT04776174,seoul
5166,5167,NCT04681365,Evaluating Bubble-PAPR for Healthcare Workers,BubblePAPR,Recruiting,No Results Available,Covid19,Other: Staff will wear and evaluate Bubble-PAP...,The primary endpoint is that participating sta...,Manchester University NHS Foundation Trust|Uni...,...,"February 24, 2021","June 1, 2021","June 2, 2021","December 23, 2020",NaN,"April 8, 2021","Manchester University NHS Foundation Trust, Ma...",NaN,https://ClinicalTrials.gov/show/NCT04681365,seoul
5193,5194,NCT04733677,User Experience of the OSR M-1,NaN,Recruiting,No Results Available,Covid19,NaN,Percentage of Successful Fits|Quality of Fit S...,Wake Forest University Health Sciences,...,"March 19, 2021",July 2021,July 2021,"February 2, 2021",NaN,"April 1, 2021","Wake Forest Baptist Health, Winston-Salem, Nor...",NaN,https://ClinicalTrials.gov/show/NCT04733677,seoul
5236,5237,NCT04812184,Adhesive Tape Placement on Patients' Masks in ...,NaN,Completed,No Results Available,Covid19,Device: Tape Face Mask,Proper face mask use up to 60 minutes|Descript...,Indiana University,...,"April 1, 2020","October 30, 2020","October 30, 2020","March 23, 2021",NaN,"March 23, 2021","Eskenazi Hospital, Indianapolis, Indiana, Unit...",NaN,https://ClinicalTrials.gov/show/NCT04812184,seoul
5237,5238,NCT04659928,Evaluation of Aerosol in a Dental Clinic,NaN,Not yet recruiting,No Results Available,Covid19,Device: High volume evacuation (HVE)|Device: E...,Number of bacterial colony forming units (CFUs...,"The University of Texas Health Science Center,...",...,"December 1, 2020","December 1, 2022","December 1, 2022","December 9, 2020",NaN,"December 9, 2020",The University of Texas Health Science Center ...,NaN,https://ClinicalTrials.gov/show/NCT04659928,seoul
5238,5239,NCT04533048,A Clinical Study to Evaluate MW33 Injection,NaN,Completed,No Results Available,Covid19,Combination Product: MW33 injection|Combinatio...,Adverse Event|Serious Adverse Event,"Mabwell (Shanghai) Bioscience Co., Ltd.|Shangh...",...,"August 7, 2020","November 16, 2020","December 2, 2020","August 31, 2020",NaN,"February 26, 2021","Shanghai Public Health Clinical Center, Shangh...",NaN,https://ClinicalTrials.gov/show/NCT04533048,seoul
5239,5240,NCT04501172,Impact of Spectacles on Compliance to Mask-wea...,NaN,Completed,No Results Available,Covid19,Behavioral: Questionnaire completion,Demographic characteristics|Compliance to mask...,Democritus University of Thrace,...,"June 25, 2020","July 24, 2020","August 14, 2020","August 6, 2020",NaN,"September 16, 2020","University Hospital of Alexandroupolis, Alexan...",NaN,https://ClinicalTrials.gov/show/NCT04501172,seoul
5240,5241,NCT04497519,Local Tolerability and Pharmacokinetic Evaluat...,NaN,Completed,No Results Available,Covid19,Drug: inhaled hydroxychloroquine,Local tolerability|Pharmacokinetic parameter,University Medical Center Groningen,...,"September 15, 2020","October 15, 2020","November 1, 2020","August 4, 2020",NaN,"November 10, 2020","University Medical Center Groningen, Groningen...",NaN,https://ClinicalTrials.gov/show/NCT04497519,seoul

In [27]:
test_or =df[(df['Rank'] > 5780) |(df['Conditions'] == 'Virus')]
test_or

,Rank,NCT Number,Title,Acronym,Status,Study Results,Conditions,Interventions,Outcome Measures,Sponsor/Collaborators,...,Start Date,Primary Completion Date,Completion Date,First Posted,Results First Posted,Last Update Posted,Locations,Study Documents,URL,city
2692,2693,NCT04393415,Using PRP and Cord Blood in Treatment of Covid...,NaN,Recruiting,No Results Available,Virus,Combination Product: stem cells,the number of patients with positive covid 19 ...,Aljazeera Hospital,...,"May 25, 2020","August 25, 2020","September 1, 2020","May 19, 2020",NaN,"July 27, 2020","Aljazeera( Al Gazeera) hospital, Giza, Egypt",NaN,https://ClinicalTrials.gov/show/NCT04393415,seoul
5780,5781,NCT04740229,Moderate-intensity Flow-based Yoga Effects on ...,NaN,Recruiting,No Results Available,Stress|Psychological,Behavioral: Yoga,Perceived Stress|Task switching paradigm|Digit...,University of Illinois at Urbana-Champaign,...,"February 10, 2021",July 2021,July 2021,"February 5, 2021",NaN,"February 24, 2021","University of Illinois at Urbana-Champaign, Ur...",NaN,https://ClinicalTrials.gov/show/NCT04740229,seoul
5781,5782,NCT04804917,3-year Follow-up of the Mind My Mind RCT,MindMyMindFU,Recruiting,No Results Available,Emotional Problem|Anxiety Disorder of Childhoo...,NaN,The child's impact of mental health problems r...,"Mental Health Services in the Capital Region, ...",...,"March 22, 2021","May 31, 2022","December 31, 2022","March 18, 2021",NaN,"April 1, 2021","Mental Health Services in the Capital Region, ...",NaN,https://ClinicalTrials.gov/show/NCT04804917,seoul
5782,5783,NCT04680000,Chronic Pain Management In Primary Care Using ...,NaN,Not yet recruiting,No Results Available,Chronic Pain,Behavioral: Brief Cognitive Behavioral Therapy...,Defense and Veterans Pain Rating Scale (DVPRS)...,The University of Texas Health Science Center ...,...,February 2021,February 2024,February 2025,"December 22, 2020",NaN,"December 22, 2020",Uniformed Services University for the Health S...,NaN,https://ClinicalTrials.gov/show/NCT04680000,seoul

In [28]:
test = df [(df[ 'Rank' ] > 5000) & ( df ['Conditions' ] == 'Covid19' ) ]
test.sort_values ('NCT Number' , ascending = False)

,Rank,NCT Number,Title,Acronym,Status,Study Results,Conditions,Interventions,Outcome Measures,Sponsor/Collaborators,...,Start Date,Primary Completion Date,Completion Date,First Posted,Results First Posted,Last Update Posted,Locations,Study Documents,URL,city
5083,5084,NCT04837755,CORONA in the Saarland,CORSAAR,Recruiting,No Results Available,Covid19,Diagnostic Test: Cytokine measurements,Correlation of biomarkers with mortality and d...,Universität des Saarlandes,...,"March 1, 2020","December 31, 2025","December 31, 2025","April 8, 2021",NaN,"April 8, 2021","Saarland University, Homburg, Saarland, Germany",NaN,https://ClinicalTrials.gov/show/NCT04837755,seoul
5236,5237,NCT04812184,Adhesive Tape Placement on Patients' Masks in ...,NaN,Completed,No Results Available,Covid19,Device: Tape Face Mask,Proper face mask use up to 60 minutes|Descript...,Indiana University,...,"April 1, 2020","October 30, 2020","October 30, 2020","March 23, 2021",NaN,"March 23, 2021","Eskenazi Hospital, Indianapolis, Indiana, Unit...",NaN,https://ClinicalTrials.gov/show/NCT04812184,seoul
5086,5087,NCT04802187,Implementation of SARS-CoV Testing Strategies ...,NaN,Recruiting,No Results Available,Covid19,Other: RADx CHCs testing intervention strategy...,Percentage increase in testing during the stud...,Massachusetts General Hospital|Dana-Farber Can...,...,"December 1, 2020","August 31, 2022","August 31, 2022","March 17, 2021",NaN,"March 17, 2021",Massachusetts League of Community Health Cente...,NaN,https://ClinicalTrials.gov/show/NCT04802187,seoul
5101,5102,NCT04776174,Efficacy and Tolerance of Telerobotic vs Stand...,NaN,Not yet recruiting,No Results Available,Covid19,Device: Ultrasound using the telerobotic Melod...,Number of normal and abnormal standard and tel...,Centre Hospitalier Intercommunal Creteil|ADECH...,...,"March 1, 2021","October 30, 2021",January 2022,"March 1, 2021",NaN,"March 1, 2021",NaN,NaN,https://ClinicalTrials.gov/show/NCT04776174,seoul
5193,5194,NCT04733677,User Experience of the OSR M-1,NaN,Recruiting,No Results Available,Covid19,NaN,Percentage of Successful Fits|Quality of Fit S...,Wake Forest University Health Sciences,...,"March 19, 2021",July 2021,July 2021,"February 2, 2021",NaN,"April 1, 2021","Wake Forest Baptist Health, Winston-Salem, Nor...",NaN,https://ClinicalTrials.gov/show/NCT04733677,seoul
5166,5167,NCT04681365,Evaluating Bubble-PAPR for Healthcare Workers,BubblePAPR,Recruiting,No Results Available,Covid19,Other: Staff will wear and evaluate Bubble-PAP...,The primary endpoint is that participating sta...,Manchester University NHS Foundation Trust|Uni...,...,"February 24, 2021","June 1, 2021","June 2, 2021","December 23, 2020",NaN,"April 8, 2021","Manchester University NHS Foundation Trust, Ma...",NaN,https://ClinicalTrials.gov/show/NCT04681365,seoul
5084,5085,NCT04681261,"Occupational Balance, Fear and Agoraphobia",OB,Completed,No Results Available,Covid19,Other: this study is not an intervention study,Occupational Balance Questionnaire,Hacettepe University,...,"May 4, 2020","June 4, 2020","June 4, 2020","December 23, 2020",NaN,"December 23, 2020","Özgü İnal, Edirne, Merkez, Turkey",NaN,https://ClinicalTrials.gov/show/NCT04681261,seoul
5237,5238,NCT04659928,Evaluation of Aerosol in a Dental Clinic,NaN,Not yet recruiting,No Results Available,Covid19,Device: High volume evacuation (HVE)|Device: E...,Number of bacterial colony forming units (CFUs...,"The University of Texas Health Science Center,...",...,"December 1, 2020","December 1, 2022","December 1, 2022","December 9, 2020",NaN,"December 9, 2020",The University of Texas Health Science Center ...,NaN,https://ClinicalTrials.gov/show/NCT04659928,seoul
5065,5066,NCT04597216,Exploration of Feasability of Blood and Saliva...,NanoDxCoV19,Recruiting,No Results Available,Covid19,Device: sample of blood and saliva,Feasibility of proteomic profile|Interest of p...,"University Hospital, Grenoble",...,"October 15, 2020","December 31, 2020","December 31, 2021","October 22, 2020",NaN,"October 22, 2020","olivier EPAULARD, Grenoble, France",NaN,https://ClinicalTrials.gov/show/NCT04597216,seoul
5238,5239,NCT04533048,A Clinical Study to Evaluate MW33 Injection,NaN,Completed,No Results Available,Covid19,Combination Product: MW33 injection|Combinatio...,Adverse Event|Serious Adverse Event,"Mabwell (Shanghai) Bioscience Co., Ltd.|Shangh...",...,"August 7, 2020","November 16, 2020","December 2, 2020","August 31, 2020",NaN,"February 26, 2021","Shanghai Public Health Clinical Center, Shangh...",NaN,https://ClinicalTrials.gov/show/NCT04533048,seoul
5239,5240,NCT04501172,Impact of Spectacles on Compliance to Mask-wea...,NaN,Completed,No Results Available,Covid19,Behavioral: Questionnaire completion,Demographic characteristics|Compliance to mask...,Democritus University of Thrace,...,"June 25, 2020","July 24, 2020","August 14, 2020","August 6, 2020",NaN,"September 16, 2020","University Hospital of Alexandroupolis, Alexan...",NaN,https://ClinicalTrials.gov/show/NCT04501172,seoul
5240,5241,NCT04497519,Local Tolerability and Pharmacokinetic Evaluat...,NaN,Completed,No Results Available,Covid19,Drug: inhaled hydroxychloroquine,Local tolerability|Pharmacokinetic parameter,University Medical Center Groningen,...,"September 15, 2020","October 15, 2020","November 1, 2020","August 4, 2020",NaN,"November 10, 2020","University Medical Center Groningen, Groningen...",NaN,https://ClinicalTrials.gov/show/NCT04497519,seoul
5100,5101,NCT04490239,Intranasal Heparin Tolerability Study,NaN,"Active, not recruiting",No Results Available,Covid19,Drug: Intranasal heparin sodium (porcine),"activated partial thromboplastin time (aPTT), ...","Joshua Sharp|University of Mississippi, Oxford",...,"October 9, 2020",November 2020,November 2020,"July 29, 2020",NaN,"October 14, 2020",The University of Mississippi National Center ...,NaN,https://ClinicalTrials.gov/show/NCT04490239,seoul

Day 10-2. 관심데이터를 그룹화 하고 요약하기

In [29]:
# HEART 데이터 경로지정
heart_path = "/Users/chae/Documents/GitHub/2023-24_Severance_Hospital/WikiDocs_의료영상_인공지능의_모든것/III_정형데이터_다루기/dataset/Heart Failure Clinical Records.csv"
df_hf = pd.read_csv(heart_path)

# HEART 데이터프레임 상위 행 5 줄 출력
df_hf.head()

,age,anaemia,creatinine_phosphokinase,diabetes,ejection_fraction,high_blood_pressure,platelets,serum_creatinine,serum_sodium,sex,smoking,time,DEATH_EVENT
0,75.0,0,582,0,20,1,265000.00,1.9,130,1,0,4,1
1,55.0,0,7861,0,38,0,263358.03,1.1,136,1,0,6,1
2,65.0,0,146,0,20,0,162000.00,1.3,129,1,1,7,1
3,50.0,1,111,0,20,0,210000.00,1.9,137,1,0,7,1
4,65.0,1,160,1,20,0,327000.00,2.7,116,0,0,8,1

In [30]:
df_hf.groupby( 'diabetes' )[ ["age", "creatinine_phosphokinase"] ].mean()

                age  creatinine_phosphokinase
diabetes
0         61.850575                589.752874
1         59.418672                570.824000

In [31]:
df_hf.groupby(['diabetes','sex'])[["smoking"]].count()

              smoking
diabetes sex
0        0         50
         1        124
1        0         55
         1         70

Day 11-1. 데이터프레임 구조 및 병합 익히기

In [32]:
df_hf = pd.read_csv(heart_path)
df_hf.head(5)

,age,anaemia,creatinine_phosphokinase,diabetes,ejection_fraction,high_blood_pressure,platelets,serum_creatinine,serum_sodium,sex,smoking,time,DEATH_EVENT
0,75.0,0,582,0,20,1,265000.00,1.9,130,1,0,4,1
1,55.0,0,7861,0,38,0,263358.03,1.1,136,1,0,6,1
2,65.0,0,146,0,20,0,162000.00,1.3,129,1,1,7,1
3,50.0,1,111,0,20,0,210000.00,1.9,137,1,0,7,1
4,65.0,1,160,1,20,0,327000.00,2.7,116,0,0,8,1

In [33]:
# 'age' 와 'creatinine_phosphokinase'의 mean (평균)
df1 = df_hf.groupby ('diabetes') [["age" , "creatinine_phosphokinase"]].mean()

# 'sex'와 'smoking' 열의 count (개수)
df2 = df_hf.groupby( 'diabetes' )[["sex" , "smoking"]].count()

df1.merge (df2 , how = 'left', on = 'diabetes')

                age  creatinine_phosphokinase  sex  smoking
diabetes
0         61.850575                589.752874  174      174
1         59.418672                570.824000  125      125

In [34]:
patient_info = pd.DataFrame({
    'Patient_ID': ['P123', 'P456', 'P789'],
    'Name': ['조태욱', '박태경', '배채원']
})

hospital_info = pd.DataFrame({
    'Patient_ID': ['P123', 'P456', 'P789'],
    'Hospital': ['내과', '피부과', '정형외과']
})

result = patient_info.set_index('Patient_ID').join(hospital_info.set_index('Patient_ID'))
result

           Name Hospital
Patient_ID
P123        조태욱       내과
P456        박태경      피부과
P789        배채원     정형외과

In [35]:
s1 = df_hf [[ 'age', 'diabetes','sex' , 'DEATH_EVENT']] .head(5)
s2 = df_hf [[ 'age', 'diabetes','sex' , 'DEATH_EVENT']] .tail(5)

In [36]:
pd.concat( [s1, s2] , ignore_index = True)

    age  diabetes  sex  DEATH_EVENT
0  75.0         0    1            1
1  55.0         0    1            1
2  65.0         0    1            1
3  50.0         0    1            1
4  65.0         1    0            1
5  62.0         1    1            0
6  55.0         0    0            0
7  45.0         1    0            0
8  45.0         0    1            0
9  50.0         0    1            0

Day 11-2. 데이터프레임의 행 / 열에 함수를 적용

In [37]:
# age 값에 + 1하여 age2에 저장
df_hf['age2'] = df_hf['age'].apply(lambda x : x + 1)
df_hf[['age','age2']].head(3)

    age  age2
0  75.0  76.0
1  55.0  56.0
2  65.0  66.0

In [38]:
import numpy as np

df_hf[['creatinine_phosphokinase' , 'serum_sodium']] = df_hf[['creatinine_phosphokinase', 'serum_sodium']].apply(np.sqrt)
df_hf[['creatinine_phosphokinase' , 'serum_sodium']].head(3)

   creatinine_phosphokinase  serum_sodium
0                 24.124676     11.401754
1                 88.662281     11.661904
2                 12.083046     11.357817

In [39]:
# id 리스트 1, 2, 3
id = [1, 2, 3]

# df_hf (Heart 데이터프레임)
age = df_hf['age'].head(3)
smoking= df_hf['smoking'].head(3)
sex = df_hf['sex'].head(3)

record = zip (id, age, smoking, sex)
list( record )

[(1, 75.0, 0, 1), (2, 55.0, 0, 1), (3, 65.0, 1, 1)]

In [40]:
id = [1, 2, 3, 4]
name= ['a','b','c','d']
record_dict = dict(zip(id, name))
print(record_dict )

{1: 'a', 2: 'b', 3: 'c', 4: 'd'}

In [41]:
print ( df_hf['smoking'].value_counts())

smoking
0    203
1     96
Name: count, dtype: int64

In [42]:
smoking= df_hf['smoking'].head(3)
smoking.map({0: 'non-smoking', 1:  'smoking'})

0    non-smoking
1    non-smoking
2        smoking
Name: smoking, dtype: object